# Generated by Django 2.1.5 on 2019-01-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkforwarding', '0002_auto_20190119_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
