# Generated by Django 2.1.5 on 2019-01-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('이슈공유', 'first'), ('장애발생', 'second'), ('이력관리', 'third'), ('기타', 'fourth')], default='이슈공유', max_length=10)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='check.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='auto_increment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='check.Post'),
        ),
    ]
