# Generated by Django 2.1.5 on 2019-01-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20190123_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_status',
            field=models.CharField(choices=[('완료', '완료'), ('진행', '진행'), ('보류', '보류')], default='ing', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('이슈공유', '이슈공유'), ('장애이력', '장애이력'), ('이력관리', '이력관리'), ('기타', '기타')], default='first', max_length=10),
        ),
    ]
