# Generated by Django 2.1.5 on 2019-01-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20190124_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_increment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Post'),
        ),
    ]
