# Generated by Django 2.1.5 on 2019-01-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-auto_increment_id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-auto_increment_id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_status',
            field=models.CharField(choices=[('완료', '완료'), ('진행', '진행'), ('보류', '보류')], default='진행', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('이슈공유', '이슈공유'), ('장애이력', '장애이력'), ('이력관리', '이력관리'), ('기타', '기타')], default='이슈공유', max_length=10),
        ),
    ]
