# Generated by Django 2.1.5 on 2019-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20190125_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_status',
            field=models.CharField(choices=[('진행', '진행'), ('완료', '완료')], default='진행', max_length=7),
        ),
    ]
